---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - git
      - libbenchmark1.8.3
      - libdisplay-info1
      - libevdev-dev
      - libgav1-1
      - libgudev-1.0-dev
      - libmtdev-dev
      - libseat1
      - libstb0
      - libwacom-dev
      - libxcb-ewmh2
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - libxmu-headers
      - libyuv0
      - libx11-xcb-dev
      - libxres-dev
      - libxmu-dev
      - libseat-dev
      - libinput-dev
      - libxcb-composite0-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-res0-dev
      - libcap-dev
      - wayland-protocols
      - libvulkan-dev
      - libwayland-dev
      - libx11-dev
      - cmake
      - pkg-config
      - meson
      - libxdamage-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxxf86vm-dev
      - libxtst-dev
      - libxkbcommon-dev
      - libdrm-dev
      - libpixman-1-dev
      - libdecor-0-dev
      - glslang-tools
      - libbenchmark-dev
      - libsdl2-dev
      - libglm-dev
      - libeis-dev
      - libavif-dev
      - hwdata
    state: present
  tags: home
  when:
    - ansible_distribution_version == "24.04"
    - ansible_os_family == "Debian"

- name: Clone the luajit repository  # noqa: latest[git] I want to have the latest
  ansible.builtin.git:
    repo: https://luajit.org/git/luajit.git
    dest: /usr/local/luajit
    version: master
  notify: Update luajit
  tags: home
  when:
    - ansible_distribution_version == "24.04"
    - ansible_os_family == "Debian"

- name: Create gamescope folder
  ansible.builtin.file:
    path: /usr/local/gamescope
    state: directory
    mode: '0777'
    owner: root
    group: root
  tags: home
  when:
    - ansible_distribution_version == "24.04"
    - ansible_os_family == "Debian"

# - name: Check if gamescope repository exists locally
#   ansible.builtin.stat:
#     path: /usr/local/gamescope/.git
#   register: gamescope_repo_stat
#   tags: home
#   when:
#     - ansible_distribution_version == "24.04"
#     - ansible_os_family == "Debian"

# - name: Clone gamescope repository
#   ansible.builtin.command: git clone https://github.com/ValveSoftware/gamescope.git /usr/local/gamescope
#   notify: Update Gamescope
#   tags: home
#   when:
#     - not gamescope_repo_stat.stat.exists
#     - ansible_distribution_version == "24.04"
#     - ansible_os_family == "Debian"

# - name: Pull latest changes from gamescope repository
#   ansible.builtin.command: git pull
#   args:
#     chdir: /usr/local/gamescope
#   notify: Update Gamescope
#   tags: home
#   when:
#     - gamescope_repo_stat.stat.exists
#     - ansible_distribution_version == "24.04"
#     - ansible_os_family == "Debian"

- name: Clone the gamescope repository  # noqa: latest[git] I want to have the latest
  ansible.builtin.git:
    repo: https://github.com/ValveSoftware/gamescope.git
    dest: /usr/local/gamescope
    # version: 3.16.2
    recursive: true
    force: true
  notify: Update Gamescope
  tags: home
  when:
    - ansible_distribution_version == "24.04"
    - ansible_os_family == "Debian"
