---
- name: Update luajit
  tags: home
  when:
    - ansible_distribution_version == "24.04"
    - ansible_os_family == "Debian"
  block:
    - name: Add '/usr/local' to git safe.directory
      community.general.git_config:
        name: safe.directory
        scope: system
        value: /usr/local

    - name: Make the project
      ansible.builtin.command: make
      args:
        chdir: /usr/local/luajit
      changed_when: true

    - name: Install the project
      ansible.builtin.command: make install
      args:
        chdir: /usr/local/luajit
      changed_when: true
