---
- name: Update keyd
  tags: always
  block:
    - name: Add '/usr/local' to git safe.directory
      community.general.git_config:
        name: safe.directory
        scope: system
        value: /usr/local

    - name: Git clean  # noqa: command-instead-of-module
      ansible.builtin.command: git clean -f
      args:
        chdir: /usr/local/keyd
      changed_when: true

    - name: Make
      ansible.builtin.command: make
      args:
        chdir: /usr/local/keyd
      changed_when: true

    - name: Make install
      ansible.builtin.command: make install
      args:
        chdir: /usr/local/keyd
      changed_when: true

    - name: Enable keyd
      ansible.builtin.systemd_service:
        name: keyd
        state: "started"
        enabled: true
