---
- name: Add udev gamepad rules
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/udev/rules.d/{{ item }}
    mode: '0644'
    owner: root
    group: root
  become: true
  loop:
    - 71-8bitdo-controllers.rules
    - 71-uinput-dev-early-creation.rules
  tags: gui

- name: Create /etc/modules-load.d/uinput.conf
  ansible.builtin.copy:
    dest: /etc/modules-load.d/uinput.conf
    content: |
      uinput
    mode: '0644'
    owner: root
    group: root
  become: true
  tags: gui

- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules
  become: true
  changed_when: true
  tags: gui

- name: Trigger new udev rules
  ansible.builtin.command: udevadm trigger
  become: true
  changed_when: true
  tags: gui
