---
- name: scrape URL for latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/{{ user }}/{{ repo }}/releases/latest
    return_content: true
  register: hack_latest
  tags: always

- name: split version out
  ansible.builtin.set_fact:
    hack_latest_version: "{{ hack_latest.json.tag_name }}"
  tags: always

- name: check if /opt/hack-nerd-font/VERSION exists
  ansible.builtin.stat:
    path: /opt/hack-nerd-font/VERSION
  register: hack_VERSION_file
  become: true
  tags: always

- name: set installed_version based on file existence
  ansible.builtin.set_fact:
    hack_installed_version: "{{ lookup('file', '/opt/hack-nerd-font/VERSION') }}"
  tags: always
  when: hack_VERSION_file.stat.exists

- name: set installed_version to 'not installed' if file does not exist
  ansible.builtin.set_fact:
    hack_installed_version: "not installed"
  tags: always
  when: not hack_VERSION_file.stat.exists

- name: display the hack version
  ansible.builtin.debug:
    msg:
      - "installed: {{ hack_installed_version }}"
      - "available: {{ hack_latest_version }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: always

- name: when there is no VERSION or it's contents don't match, do these
  block:
    - name: delete previous version
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent
      with_items:
        - /usr/share/fonts/truetype/hack-nerd-font
        - /opt/hack-nerd-font

    - name: create empty folders
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /usr/share/fonts/truetype/hack-nerd-font
        - /opt/hack-nerd-font

    - name: Download Hack
      ansible.builtin.unarchive:
        src: https://github.com/{{ user }}/{{ repo }}/releases/download/{{ hack_latest_version }}/Hack.zip
        dest: "/usr/share/fonts/truetype/hack-nerd-font"
        remote_src: yes
      register: hack_download

    - name: add VERSION file
      ansible.builtin.copy:
        content: "{{ hack_latest_version }}"
        dest: /opt/hack-nerd-font/VERSION
      when: hack_download is not failed
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  tags: always
  when: hack_installed_version != hack_latest_version
