---
- name: Ensure HibernateDelaySec is set in sleep.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/sleep.conf
    line: "HibernateDelaySec=900"
    create: true
    mode: "0440"
  become: true
  tags: always

- name: Ensure AllowSuspendThenHibernate is set in sleep.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/sleep.conf
    line: "AllowSuspendThenHibernate=yes"
    create: true
    mode: "0440"
  become: true
  tags: always

- name: Ensure HandleLidSwitch is set in logind.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: "HandleLidSwitch=hibernate"
    create: true
    mode: "0440"
  become: true
  tags: laptop

- name: Ensure HandleSuspendKey is set in logind.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: "HandleSuspendKey=suspend-then-hibernate"
    create: true
    mode: "0440"
  become: true
  tags: always

- name: Create /etc/polkit-1/localauthority/10-vendor.d directory if it does not exist
  ansible.builtin.file:
    path: /etc/polkit-1/localauthority/10-vendor.d
    state: directory
    mode: "0440"
  become: true
  tags: always

# TODO: doesn't seem to work in cosmic
- name: Create com.ubuntu.pkla
  ansible.builtin.copy:
    dest: /etc/polkit-1/localauthority/10-vendor.d/com.ubuntu.pkla
    content: |
      [Enable hibernate in upower]
      Identity=unix-user:*
      Action=org.freedesktop.upower.hibernate
      ResultActive=yes

      [Enable hibernate in logind]
      Identity=unix-user:*
      Action=org.freedesktop.login1.hibernate;org.freedesktop.login1.handle-hibernate-key;org.freedesktop.login1;org.freedesktop.login1.hibernate-multiple-sessions;org.freedesktop.login1.hibernate-ignore-inhibit
      ResultActive=yes
    mode: "0440"
  become: true
  tags: always

- name: Ensure the user can suspend without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/sleepstates
    line: "{{ main_user }} ALL=NOPASSWD: /bin/systemctl suspend"
    create: true
    mode: "0440"
  become: true
  tags: always

- name: Ensure the user can hibernate without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/sleepstates
    line: "{{ main_user }} ALL=NOPASSWD: /bin/systemctl hibernate"
    create: true
    mode: "0440"
  become: true
  tags: always

- name: Ensure the user can suspend-then-hibernate without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/sleepstates
    line: "{{ main_user }} ALL=NOPASSWD: /bin/systemctl suspend-then-hibernate"
    create: true
    mode: "0440"
  become: true
  tags: always

- name: Dconf requirement installation
  ansible.builtin.apt:
    state: present
    name: python3-psutil
  become: true
  tags: laptop

- name: Configure sleep-inactive-ac-type
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
    value: "'suspend'"
    state: present
  tags: laptop

- name: Configure sleep-inactive-ac-timeout
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: 7200
    state: present
  tags: laptop

- name: Configure sleep-inactive-battery-type
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type"
    value: "'suspend-then-hibernate'"
    state: present
  tags: laptop

- name: Configure sleep-inactive-battery-timeout
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout"
    value: 900
    state: present
  tags: laptop
