---
- name: set timezone to Europe/Brussels
  timezone:
    name: Europe/Brussels
  tags: always

- name: add Hack nerdfont
  ansible.builtin.include_tasks:
    file: hack-font.yml
  vars:
    user: "ryanoasis"
    repo: "nerd-fonts"
  tags: always

- name: configure firewall rules
  ansible.builtin.include_tasks:
    file: firewall.yml
  tags: always

- name: configure hibernation
  ansible.builtin.include_tasks:
    file: hibernation.yml
  tags: always
  when: ("gui" is in ansible_run_tags)

- name: configure automatic switch batterty and ac profile
  ansible.builtin.include_tasks:
    file: autopowerprofile.yml
  tags: always

- name: upgrade recovery partition
  block:
    - name: "upgrade recovery partition : check the current day"
      ansible.builtin.shell: "echo $(($(date '+%d')%7))"
      register: current_day

    - name: "upgrade recovery partition : execute upgrade"
      ansible.builtin.command: pop-upgrade recovery upgrade from-release
      ignore_errors: "{{ ansible_check_mode }}"
      when: current_day.stdout | int == 1
  tags: always
  when:
    - ansible_distribution == "Pop!_OS"
    - ansible_distribution_version == "22.04"

- name: add arrpc
  ansible.builtin.include_tasks:
    file: arrpc.yml
  vars:
    user: "OpenAsar"
    repo: "arrpc"
  tags: home

- name: add syncthing
  ansible.builtin.include_tasks:
    file: syncthing.yml
  tags: home

- name: add fw-fanctrl
  ansible.builtin.include_tasks:
    file: fw-fanctrl.yml
  vars:
    user: "MyNameIs-13"
    repo: "fw-fanctrl"
  tags: framework

- name: add noise-suppression-for-voice
  ansible.builtin.include_tasks:
    file: noise-suppression-for-voice.yml
  vars:
    user: "werman"
    repo: "noise-suppression-for-voice"
  tags: home
