---
- name: set timezone to Europe/Brussels
  timezone:
    name: Europe/Brussels
  tags: always

- name: configure firewall rules
  ansible.builtin.include_tasks:
    file: firewall.yml
  tags: always

- name: configure hibernation
  ansible.builtin.include_tasks:
    file: hibernation.yml
  tags: always
  when: ("gui" is in ansible_run_tags)

- name: configure automatic switch batterty and ac profile
  ansible.builtin.include_tasks:
    file: autopowerprofile.yml
  tags: always

- name: upgrade recovery partition
  block:
    - name: check the current day
      ansible.builtin.shell: "echo $(($(date '+%d')%7))"
      register: current_day

    - name: execute upgrade
      ansible.builtin.command: pop-upgrade recovery upgrade from-release
      ignore_errors: "{{ ansible_check_mode }}"
      when: current_day.stdout | int == 1
  tags: always
  when:
    - ansible_distribution == "Pop!_OS"
    - ansible_distribution_version == "22.04"
