---
- name: Set timezone to Europe/Brussels
  community.general.timezone:
    name: Europe/Brussels
  tags: always

- name: Install requirements
  ansible.builtin.apt:
    name:
      - git
      - npm
    state: present
  tags: always

- name: Add Hack nerdfont
  ansible.builtin.include_tasks:
    file: hack-font.yml
  vars:
    user: "ryanoasis"
    repo: "nerd-fonts"
  tags: always

- name: Configure firewall rules
  ansible.builtin.include_tasks:
    file: firewall.yml
  tags: always

- name: Configure hibernation
  ansible.builtin.include_tasks:
    file: hibernation.yml
  tags: always
  when: ("gui" is in ansible_run_tags)

- name: Configure automatic switch batterty and ac profile
  ansible.builtin.include_tasks:
    file: autopowerprofile.yml
  tags: always

- name: Clone the arrpc repository  # noqa: latest[git] I want to have the latest
  ansible.builtin.git:
    repo: https://github.com//OpenAsar/arrpc.git
    dest: /usr/local/arrpc
    version: main
  notify:
    - Add '/usr/local' to git safe.directory
    - Update arrpc
  ignore_errors: "{{ ansible_check_mode }}"
  tags: gui

- name: Add syncthing
  ansible.builtin.include_tasks:
    file: syncthing.yml
  tags: home

- name: Clone the fw-fanctrl repository  # noqa: latest[git] I want to have the latest
  ansible.builtin.git:
    repo: https://github.com/MyNameIs-13/fw-fanctrl.git
    dest: /usr/local/fw-fanctrl
    version: main
  notify:
    - Add '/usr/local' to git safe.directory
    - Update framework fancontrol
  tags: laptop
  when:
    - ansible_hostname == "framework"

- name: Ensure the user can use ectool
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/ectool
    line: "{{ main_user }} ALL=NOPASSWD: /usr/bin/ectool*"
    create: true
    mode: '0440'
    owner: root
    group: root
  tags: laptop
  when:
    - ansible_hostname == "framework"

- name: Add noise-suppression-for-voice
  ansible.builtin.include_tasks:
    file: noise-suppression-for-voice.yml
  vars:
    user: "werman"
    repo: "noise-suppression-for-voice"
  tags: home

- name: Mount mean-machine drives
  ansible.builtin.include_tasks:
    file: mount-drives.yml
  tags: always

- name: Mount mean-machine drives
  ansible.builtin.include_tasks:
    file: mount-drives.yml
  tags: always

- name: Remove /root/.bashrc if it isn't a symlink, then create symlink
  tags: always
  block:
    - name: Check if /root/.bashrc is a symlink
      ansible.builtin.stat:
        path: /root/.bashrc
        follow: false
      register: root_bashrc

    - name: Remove /root/.bashrc if it isn't a symlink
      ansible.builtin.file:
        path: /root/.bashrc
        state: absent
      when:
        - root_bashrc.stat.exists
        - not root_bashrc.stat.islnk

    - name: Create a symbolic link to .bashrc in /home/{{ main_user }}
      ansible.builtin.file:
        src: /home/{{ main_user }}/.bashrc
        dest: /root/.bashrc
        force: true
        state: link

- name: Remove /root/.vimrc if it isn't a symlink, then create symlink
  tags: always
  block:
    - name: Check if /root/.vimrc is a symlink
      ansible.builtin.stat:
        path: /root/.vimrc
        follow: false
      register: root_vimrc

    - name: Remove /root/.vimrc if it isn't a symlink
      ansible.builtin.file:
        path: /root/.vimrc
        state: absent
      when:
        - root_vimrc.stat.exists
        - not root_vimrc.stat.islnk

    - name: Create a symbolic link to .vimrc in /home/{{ main_user }}
      ansible.builtin.file:
        src: /home/{{ main_user }}/.vimrc
        dest: /root/.vimrc
        force: true
        state: link
