---
- name: Mount mean-machine drives
  become: true
  tags: desktop
  when: ("mean-machine" in ansible_hostname)
  block:
    - name: Mount games disk
      ansible.posix.mount:
        path: /home/skodo/games
        src: /dev/disk/by-label/Games
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted
        dump: 0
        passno: 0

    - name: Mount archive partition
      ansible.posix.mount:
        path: /home/skodo/archive
        src: /dev/mapper/archive
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted
        dump: 0
        passno: 0

    - name: Mount virtual-machines partition
      ansible.posix.mount:
        path: /home/skodo/virtual-machines
        src: /dev/mapper/virtual-machines
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted
        dump: 0
        passno: 0
