---
- name: Scrape URL for latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/{{ user }}/{{ repo }}/releases/latest
    return_content: true
  register: nsfv_latest
  tags: home

- name: Split version out
  ansible.builtin.set_fact:
    nsfv_latest_version: "{{ nsfv_latest.json.tag_name }}"
  tags: home

- name: Check if /usr/local/noise-suppression-for-voice/VERSION exists
  ansible.builtin.stat:
    path: /usr/local/noise-suppression-for-voice/VERSION
  register: nsfv_version_file
  tags: home

- name: Set installed_version based on file existence
  ansible.builtin.set_fact:
    nsfv_installed_version: "{{ lookup('file', '/usr/local/noise-suppression-for-voice/VERSION') }}"
  tags: home
  when: nsfv_version_file.stat.exists

- name: Set installed_version to 'not installed' if file does not exist
  ansible.builtin.set_fact:
    nsfv_installed_version: "not installed"
  tags: home
  when: not nsfv_version_file.stat.exists

- name: Display the nsfv version
  ansible.builtin.debug:
    msg:
      - "installed: {{ nsfv_installed_version }}"
      - "available: {{ nsfv_latest_version }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: home

- name: When there is no VERSION or it's contents don't match, do these
  ignore_errors: "{{ ansible_check_mode }}"
  tags: home
  when: nsfv_installed_version != nsfv_latest_version
  block:
    - name: Delete previous version
      ansible.builtin.file:
        name: /usr/local/noise-suppression-for-voice
        state: absent

    - name: Create empty folder
      ansible.builtin.file:
        path: /usr/local/noise-suppression-for-voice
        state: directory
        mode: '0777'
        owner: root
        group: root

    - name: Download nsfv
      ansible.builtin.unarchive:
        src: https://github.com/{{ user }}/{{ repo }}/releases/download/{{ nsfv_latest_version }}/linux-rnnoise.zip
        dest: "/usr/local/noise-suppression-for-voice"
        remote_src: true
        mode: '0777'
        owner: root
        group: root
      register: nsfv_download
      until: "nsfv_download is not failed"
      retries: 3
      delay: 10


    - name: Add VERSION file
      ansible.builtin.copy:
        content: "{{ nsfv_latest_version }}"
        dest: /usr/local/noise-suppression-for-voice/VERSION
        mode: '0644'
        owner: root
        group: root
      when: nsfv_download is not failed
