---
- name: scrape URL for latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/{{ user }}/{{ repo }}/releases/latest
    return_content: true
  register: latest
  tags: common

- name: split version out
  ansible.builtin.set_fact:
    latest_version: "{{ latest.json.tag_name }}"
  tags: common

- name: check if /opt/zed.app/VERSION exists
  ansible.builtin.stat:
    path: /opt/zed.app/VERSION
  register: VERSION_file
  become: true
  tags: common

- name: set installed_version based on file existence
  ansible.builtin.set_fact:
    installed_version: "{{ lookup('file', '/opt/zed.app/VERSION') }}"
  when: VERSION_file.stat.exists
  tags: common

- name: set installed_version to 'not installed' if file does not exist
  ansible.builtin.set_fact:
    installed_version: "not installed"
  when: not VERSION_file.stat.exists
  tags: common

- name: display the zed-editor version
  ansible.builtin.debug:
    msg: 
      - "installed: {{ installed_version }}"
      - "available: {{ latest_version }}"
  tags: common

- name: when there is no VERSION or it's contents don't match, do these
  block:
    - name: delete previous version
      ansible.builtin.file:
        path: /opt/zed.app
        state: absent

    - name: download and extract tarball
      ansible.builtin.unarchive:
        src: https://github.com/{{ user }}/{{ repo }}/releases/download/{{ latest_version }}/zed-linux-x86_64.tar.gz
        dest: /opt
        remote_src: yes
        mode: '0755'
      
    - name: add VERSION file
      ansible.builtin.copy:
        content: "{{ latest_version }}"
        dest: /opt/zed.app/VERSION      

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /opt/zed.app/bin/zed
        dest: /usr/local/bin/zed
        state: link

    - name: create desktop file
      ansible.builtin.copy:
        dest: /usr/share/applications/dev.zed.Zed.desktop
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=Zed
          GenericName=Text Editor
          Comment=A high-performance, multiplayer code editor.
          TryExec=/opt/zed.app/libexec/zed-editor
          StartupNotify=true
          Exec=/opt/zed.app/libexec/zed-editor %U
          Icon=/opt/zed.app/share/icons/hicolor/512x512/apps/zed.png
          Categories=Utility;TextEditor;Development;IDE;
          Keywords=zed;
          MimeType=text/plain;inode/directory;x-scheme-handler/zed;
          Actions=NewWorkspace;

          [Desktop Action NewWorkspace]
          Exec=/opt/zed.app/libexec/zed-editor --new %U
          Name=Open a new workspace
          
    #https://github.com/zed-industries/zed/issues/15629#issuecomment-2277029842
    - name: workaround for pop!_os nvidia stuff
      ansible.builtin.lineinfile:
        path: /etc/prime-discrete
        regexp: '^on'
        line: 'off'
  become: true
  tags: common
  when: installed_version != latest_version
