---
# enable only the role which should be testes/debugged
- hosts: all
  
  roles:
    # - configure_system
    # - apt
    # - ohmyposh
    # - joplin
    - zed-editor
    # - pycharm
    # - gamescope