---
# enable only the role which should be testes/debugged
- hosts: all
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    # - name: Distribution major version
    #   debug: msg="{{ ansible_distribution_major_version }}"
  roles:
    # - configure_system
    # - apt
    # - ohmyposh
    # - joplin
    # - zed-editor
    # - rustdesk
    # - pycharm
    - role: gamescope
      when: ansible_distribution_version == "24.04"
