---
- hosts: all
  vars:
    main_user: "skodo"
  roles:
    - role: configure_system
    - role: apt
      when: ansible_os_family == "Debian"
    - role: ohmyposh
    - role: chezmoi
    - role: joplin
    - role: keyd
    - role: zed-editor
    - role: rustdesk
      when: ansible_os_family == "Debian"
    - role: pycharm
    - role: gamescope
      when:
        - ansible_distribution_version == "24.04"
        - ansible_os_family == "Debian"
