---
- name: Install
  hosts: control_node
  vars:
    main_user: "skodo"
  roles:
    - role: apt
    - role: configure_system
    - role: ohmyposh
    - role: chezmoi
    - role: joplin
    - role: keyd
    - role: zed_editor
    - role: rustdesk
    - role: pycharm
    - role: gamescope
    - role: pop_keyboard_shortcuts
