---
- name: Add brave repo and install
  tags: gui
  when: ansible_architecture == "x86_64"
  block:
    - name: Add brave apt repository
      ansible.builtin.deb822_repository:
        name: brave-browser-release
        types: deb
        uris: https://brave-browser-apt-release.s3.brave.com/
        suites: stable
        components: main
        architectures: amd64
        signed_by: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

    - name: Install brave browser
      ansible.builtin.apt:
        state: present
        name: brave-browser
      ignore_errors: "{{ ansible_check_mode }}" # --check cannot validate that the package is available as the repo is not yet added

    - name: Add initial_preferences
      ansible.builtin.template:
        src: brave-settings.j2
        dest: /opt/brave.com/brave/initial_preferences
        mode: '0666'
        owner: root
        group: root

    - name: Add bookmarks
      ansible.builtin.template:
        src: brave-bookmarks.html.j2
        dest: /opt/brave.com/brave/bookmarks.html
        mode: '0666'
        owner: root
        group: root

    - name: Create extensions folder
      ansible.builtin.file:
        path: /opt/brave.com/brave/extensions
        state: directory
        mode: '0777'
        owner: root
        group: root

    - name: Add extensions
      ansible.builtin.copy:
        dest: /opt/brave.com/brave/extensions/{{ item }}.json
        content: |
          {
            "external_update_url": "https://clients2.google.com/service/update2/crx"
          }
        mode: '0666'
        owner: root
        group: root
      with_items:
        - "oboonakemofpalcgghocfoadofidjkkk" # keepassxc
        - "danncghahncanipdoajmakdbeaophenb" # auto-group-tabs
        - "fploionmjgeclbkemipmkogoaohcdbig" # page-load-time
