---
- name: apt
  block:
    - name: run the equivalent of "apt-get update"
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      ignore_errors: true # sometimes fails due to 'unkown reason'
      tags: always

    - name: add brave browser
      ansible.builtin.include_tasks:
        file: brave.yml
      tags: gui

    - name: add Minimon COSMIC Applet
      ansible.builtin.include_tasks:
        file: minimon-applet.yml
      vars:
        user: "Hyperchaotic"
        repo: "minimon-applet"
      tags: laptop,vm

    - name: install vesktop.deb package
      ansible.builtin.apt:
        deb: https://vencord.dev/download/vesktop/amd64/deb
      register: vesktop_download
      until: "vesktop_download is not failed"
      retries: 3
      delay: 10
      ignore_errors: true
      tags: gui
      when: ansible_architecture == "x86_64"

    - name: remove a list of packages
      ansible.builtin.apt:
        state: absent
        pkg:
          - firefox
          - totem
      tags: always

    - name: install common command line tools and libs
      ansible.builtin.apt:
        state: present
        pkg:
          - age
          - lm-sensors
          - keyutils
          - tar
          - wget
          - jq
          - curl
          - git
          - unzip
          - vim
          - gnupg
          - lsb-release
          - apt-transport-https
          - ca-certificates
          - python3-pip
          - python3-github
          - python3-venv
          - python3-psutil
          - libsdl2-2.0-0
          - libsdl2-image-2.0-0
          - libsecret-tools
          - libsecret-1-dev
          - libsecret-1-0
          - software-properties-common
          - plocate
          - golang-go
          - libxkbcommon-dev
          - p7zip
          - npm
      tags: always

    - name: make git-credential-libsecret
      ansible.builtin.command: make
      args:
        chdir: /usr/share/doc/git/contrib/credential/libsecret
      tags: always

    - name: install common command line tools and libs (24.04)
      ansible.builtin.apt:
        state: present
        pkg:
          - git-credential-oauth
      tags: always
      when: ansible_distribution_version == "24.04"

    - name: install common command line tools and libs
      ansible.builtin.apt:
        state: present
        pkg:
          - ansible
          - fprintd
          - libpam-fprintd
          - nala
          - libsdl2-2.0-0
          - libsdl2-image-2.0-0
          - gir1.2-gst-plugins-base-1.0
          - texlive-base
          - texlive-binaries
          - texlive-extra-utils
          - texlive-fonts-recommended
          - texlive-lang-german
          - texlive-lang-greek
          - texlive-latex-base
          - texlive-latex-extra
          - texlive-latex-recommended
          - texlive-luatex
          - texlive-pictures
          - texlive-plain-generic
          - texlive-science
          - texlive-xetex
      tags: gui

    - name: install common gui applications
      ansible.builtin.apt:
        state: present
        pkg:
          - celluloid
          - obs-studio
          - kdenlive
          - rpi-imager
          - pavucontrol
          - code
          - keepassxc
          - gimp
          - texstudio
          - kdeconnect
      tags: gui

    - name: install home specific command line tools and libs
      ansible.builtin.apt:
        state: present
        pkg:
          - gamemode
          - mangohud
          - mangoapp
      tags: home
      when:
        - ("gui" is in ansible_run_tags)
        - ansible_distribution_version == "24.04"

    - name: install home specific gui applications
      ansible.builtin.apt:
        state: present
        pkg:
          - lutris
          - steam
          - conky-all
          - nextcloud-desktop
          - virt-manager
      tags: home
      when: ("gui" is in ansible_run_tags)

    - name: install virtual machine tools
      ansible.builtin.apt:
        state: present
        pkg:
          - open-vm-tools
          - open-vm-tools-desktop
          - spice-vdagent
          - spice-webdavd
      tags: gui
      when: ("vm" is in ansible_hostname)

    - name: update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
      tags: always

    - name: List installed and updated packages
      shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: updated_packages
      tags: always

    - name: Show Output
      debug: msg="{{ updated_packages.stdout_lines }}"
      tags: always

    - name: remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.apt:
        autoremove: true
        purge: true
      tags: always

    - name: run the equivalent of "apt-get autoclean"
      ansible.builtin.apt:
        autoclean: true
      tags: always

    - name: run the equivalent of "apt-get autoclean"
      ansible.builtin.apt:
        clean: true
      tags: always
      when: ansible_distribution_version == "24.04"
  become: true
  when: ansible_os_family == "Debian"
