---
- name: Apt
  become: true
  when: ansible_os_family == "Debian"
  block:
    - name: Add ansible repository into sources list
      ansible.builtin.apt_repository:
        repo: ppa:ansible/ansible
        state: present
      tags: always

    - name: Run the equivalent of "apt-get update"
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      failed_when: false # sometimes fails due to 'unkown reason'
      tags: always

    - name: Add brave browser
      ansible.builtin.include_tasks:
        file: brave.yml
      tags: gui

    - name: Add Minimon COSMIC Applet
      ansible.builtin.include_tasks:
        file: minimon-applet.yml
      vars:
        user: "Hyperchaotic"
        repo: "minimon-applet"
      tags: laptop,vm

    - name: Add Gamemode COSMIC Applet
      ansible.builtin.include_tasks:
        file: gamemode-applet.yml
      vars:
        user: "D-Brox"
        repo: "cosmic-ext-applet-gamemode-status"
      tags: gui

    - name: Install vesktop.deb package
      ansible.builtin.apt:
        deb: https://vencord.dev/download/vesktop/amd64/deb
      register: vesktop_download
      until: "vesktop_download is not failed"
      retries: 3
      delay: 10
      failed_when: false
      notify: List installed and updated apt packages
      tags: gui
      when: ansible_architecture == "x86_64"

    - name: Remove a list of packages
      ansible.builtin.apt:
        state: absent
        pkg:
          - firefox
          - totem
      notify: List installed and updated apt packages
      tags: always

    - name: Install common command line tools and libs
      ansible.builtin.apt:
        state: present
        pkg:
          - age
          - lm-sensors
          - keyutils
          - tar
          - wget
          - jq
          - curl
          - git
          - unzip
          - vim
          - gnupg
          - lsb-release
          - apt-transport-https
          - ca-certificates
          - python3-pip
          - python3-github
          - python3-venv
          - python3-psutil
          - libsdl2-2.0-0
          - libsdl2-image-2.0-0
          - git-credential-oauth
          - software-properties-common
          - plocate
          - golang-go
          - libxkbcommon-dev
          - p7zip
          - npm
          - cargo
          - rustc
          - libgtk-3-dev
          - just
          - ansible-lint
      notify: List installed and updated apt packages
      tags: always

    - name: Install libsecret command line tools and libs
      ansible.builtin.apt:
        state: present
        pkg:
          - libsecret-tools
          - libsecret-1-dev
          - libsecret-1-0
      notify:
        - Make git-credential-libsecret
        - List installed and updated apt packages
      tags: always

    - name: Install common command line tools and libs
      ansible.builtin.apt:
        state: present
        pkg:
          - ansible
          - fprintd
          - libpam-fprintd
          - nala
          - libsdl2-2.0-0
          - libsdl2-image-2.0-0
          - gir1.2-gst-plugins-base-1.0
          - texlive-base
          - texlive-binaries
          - texlive-extra-utils
          - texlive-fonts-recommended
          - texlive-lang-german
          - texlive-lang-greek
          - texlive-latex-base
          - texlive-latex-extra
          - texlive-latex-recommended
          - texlive-luatex
          - texlive-pictures
          - texlive-plain-generic
          - texlive-science
          - texlive-xetex
      notify: List installed and updated apt packages
      tags: gui

    - name: Install common gui applications
      ansible.builtin.apt:
        state: present
        pkg:
          - celluloid
          - obs-studio
          - kdenlive
          - rpi-imager
          - pavucontrol
          - code
          - keepassxc
          - gimp
          - texstudio
          - kdeconnect
      notify: List installed and updated apt packages
      tags: gui

    - name: Install home specific gui applications
      ansible.builtin.apt:
        state: present
        pkg:
          - lutris
          - steam
          - conky-all
          - nextcloud-desktop
          - virt-manager
          - gamemode
          - mangohud
          - mangoapp
      notify: List installed and updated apt packages
      tags: home
      when: ("gui" is in ansible_run_tags)

    - name: Install virtual machine tools
      ansible.builtin.apt:
        state: present
        pkg:
          - open-vm-tools
          - open-vm-tools-desktop
          - spice-vdagent
          - spice-webdavd
      notify: List installed and updated apt packages
      tags: gui
      when: ("vm" is in ansible_hostname)

    - name: Update all packages to their latest version  # noqa: package-latest
      ansible.builtin.apt:
        name: "*"
        state: latest
      notify: List installed and updated apt packages
      tags: always

    - name: Remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.apt:
        autoremove: true
        purge: true
      tags: always

    - name: Run the equivalent of "apt-get autoclean"
      ansible.builtin.apt:
        autoclean: true
      tags: always

    - name: Run the equivalent of "apt-get clean"
      ansible.builtin.apt:
        clean: true
      tags: always
