---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - git
      - cargo
      - rustc
      - just
      - lm-sensors
    state: present
  tags: laptop,vm

- name: Clone the minimon repository  # noqa: latest[git] I want to have the latest
  ansible.builtin.git:
    repo: https://github.com/{{ user }}/{{ repo }}.git
    dest: /usr/local/minimon-applet
    version: main
  notify: Update Minimon Applet
  ignore_errors: "{{ ansible_check_mode }}"
  tags: laptop,vm
