---
- name: Update Minimon Applet
  tags: always
  block:
    - name: Add '/usr/local' to git safe.directory
      community.general.git_config:
        name: safe.directory
        scope: system
        value: /usr/local

    - name: Remove old builds and build attempts
      ansible.builtin.file:
        state: absent
        dest: /usr/local/minimon-applet/target

    - name: Build project minimon
      ansible.builtin.command: just build-release
      args:
        chdir: /usr/local/minimon-applet
      changed_when: true

    - name: Install project
      ansible.builtin.command: just install
      args:
        chdir: /usr/local/minimon-applet
      changed_when: true
